name: ci
on:
  - push
  - pull_request
jobs:

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    strategy:
      matrix:
        package:
          - bundle
          - crypto
          - diff
          - logger
          - qrcode
          - typing
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: deno task publish:${{ matrix.package }}
